//BUZZ ACTION TYPE
export const ADD_BUZZ = "ADD_BUZZ";
export const SHOW_BUZZ = "SHOW_BUZZ";
export const PUT_LIKE = 'PUT_LIKE';
export const PUT_DISLIKE = 'PUT_DISLIKE';

//COMPLAINT ACTION TYPE
export const ADD_COMPLAINT = "ADD_COMPLAINT";
export const SHOW_COMPLAINT = "SHOW_COMPLAINT";

//RESOLVE ACTION TYPE
export const UPDATE_COMPLAINT_STATUS = "UPDATE_COMPLAINT_STATUS";

//USER ACTION TYPE
export const SHOW_USER = "SHOW_USER";